import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Recursive,
  Roboto,
  Literata,
  Darker_Grotesque,
} from "next/font/google";
import { Viaoda_Libre } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Providers from "./(main)/components/Providers";
import { Toaster } from "@/components/ui/toaster";
import { AppLoadingProvider } from "@/components/app-loading-provider";
import { AuthWrapper } from "@/components/auth-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const recursive = Roboto({
  variable: "--font-recursive",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

const darkerGrotesque = Darker_Grotesque({
  variable: "--font-darker-grotesque",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});

const literata = Literata({
  variable: "--font-literata",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

const viaodalLibre = Viaoda_Libre({
  variable: "--font-viaoda-libre",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Trainly - The AI expert for your personal use case",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${recursive.variable} ${literata.variable} ${darkerGrotesque.variable} ${viaodalLibre.variable}
           antialiased dark:bg-lightmaincolor
          bg-white scrollbar-hide overscroll-none`}
      >
        <Providers>
          <AppLoadingProvider>
            <main>
              <Toaster />
              {children}
            </main>
          </AppLoadingProvider>
        </Providers>
      </body>
    </html>
  );
}
