import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Recursive,
  Roboto,
  Literata,
} from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import { ClerkProvider } from "@clerk/clerk-react";
import { ConvexClient } from "convex/browser";
import { ConvexClientProvider } from "./components/providers/convex-provider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./(main)/components/sidebar";
import { useEffect } from "react";
import { ThemeProvider } from "next-themes";
import ThemeSwitcher from "./(main)/components/theme-switcher";
import Providers from "./(main)/components/Providers";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const recursive = Roboto({
  variable: "--font-recursive",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

const literata = Literata({
  variable: "--font-literata",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Trainly - The AI expert for your personal use case",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${recursive.variable} ${literata.variable} antialiased dark:bg-lightmaincolor
          bg-white scrollbar-hide overscroll-none`}
      >
        <Providers>
          <main>
            <Navbar />
            <Toaster />

            {/* <main> */}
            {/* <SidebarTrigger /> */}
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
