name: ci-hypermode-functions

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  MODUS_DIR: ""

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List repository files
        run: |
          echo "Listing all files in the repository:"
          ls -R

      - name: Locate directory with modus.json
        id: set-dir
        run: |
          MODUS_JSON=$(find . -type f -name 'modus.json' -print -quit)
          if [ -n "$MODUS_JSON" ]; then
            MODUS_DIR=modus/api
            echo "MODUS_DIR=$MODUS_DIR" >> $GITHUB_ENV
          else
            echo "modus.json not found"
            exit 1
          fi

      # Alternatively, if the path is fixed, use the following instead of the Locate step:
      # - name: Set MODUS_DIR
      #   run: echo "MODUS_DIR=modus/api" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Setup TinyGo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: "0.34.0"

      - name: Build project
        run: npx -p @hypermode/modus-cli -y modus build
        working-directory: ${{ env.MODUS_DIR }}
        shell: bash

      - name: Publish GitHub artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ env.MODUS_DIR }}/build/*
